name: DevEnv Tests

on:
  push:
    branches: [ "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
     
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-23.05

      - uses: cachix/cachix-action@v16
        with:
          name: codetetic-php
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - uses: actions/cache/restore@v3
        id: cache-vendor
        with:
          path: vendor
          key: ${{ runner.os }}-vendor-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-vendor-

      - name: Run devenv tests
        run: nix run nixpkgs#devenv test

      - uses: actions/cache/save@v3
        if: success()
        with:
          path: vendor
          key: ${{ runner.os }}-vendor-${{ hashFiles('**/composer.lock') }}
